### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by omerjerk** [omerjerk/hello-8080#1]
- [ ] Fix some glitches in the graphics.
- [ ] Implement sound subsystem.
- [ ] Implement basic controls using the keyboard.
